# Generated by Django 4.2.4 on 2023-08-31 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_mailinglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name_plural': 'Mailing List'},
        ),
    ]
