# Generated by Django 4.2.4 on 2023-09-02 20:11
# Mark Witt / Brittany Kyncl
# CSD-440: Capstone Project
# Moffat-Bay Lodge - Bravo Team

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
            ],
            options={
                'verbose_name_plural': 'Mailing List',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'User Accounts'},
        ),
    ]
