# Generated by Django 4.2.4 on 2023-08-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zip',
            field=models.CharField(max_length=6),
        ),
    ]
