# Generated by Django 4.2.4 on 2023-08-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stay_costs',
            options={'verbose_name_plural': 'Nightly Costs'},
        ),
    ]
