# Generated by Django 4.2.4 on 2023-09-04 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('confirmationKey', models.CharField(max_length=8)),
                ('guests', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField()),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.rooms')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Guest Reservations',
            },
        ),
    ]
