# Generated by Django 4.2.4 on 2023-08-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_stay_costs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomsChoices',
            fields=[
                ('choiceID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('roomSize', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Room Size Choices',
            },
        ),
    ]
