# Generated by Django 4.2.4 on 2023-08-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_roomschoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsChoices',
            new_name='RoomChoices',
        ),
    ]
