# Generated by Django 4.2.4 on 2023-09-06 14:58
# Mark Witt / Brittany Kyncl
# CSD-440: Capstone Project
# Moffat-Bay Lodge - Bravo Team

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservations_confirmationkey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='confirmationKey',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='reservationID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
