# Generated by Django 4.2.4 on 2023-08-31 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_roomschoices_roomchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomchoices',
            name='roomSize',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('roomID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.roomchoices', to_field='roomSize')),
            ],
            options={
                'verbose_name_plural': 'Lodge Rooms',
            },
        ),
    ]
