# Generated by Django 4.2.4 on 2023-08-31 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_roomchoices_roomsize_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.roomchoices'),
        ),
    ]
