# Generated by Django 4.2.4 on 2023-09-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_rooms_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='size',
        ),
        migrations.DeleteModel(
            name='RoomChoices',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
